import type { L10n } from "@/lib/i18n";

export const dash = {
  brand: "Malki",
  login: {
    title: { fr: "Connexion", ar: "تسجيل الدخول" } satisfies L10n,
    body: {
      fr: "Nouvel élève ou déjà inscrit : entrez votre email. Nous envoyons un code à 6 chiffres — aucun mot de passe. Un compte se crée automatiquement au premier code validé.",
      ar: "طالب جديد أو عائد: أدخل بريدك. نرسل رمزاً من 6 أرقام — بدون كلمة مرور. يُنشأ الحساب تلقائياً عند أول رمز صحيح.",
    } satisfies L10n,
    email: { fr: "Email", ar: "البريد الإلكتروني" } satisfies L10n,
    send: { fr: "Envoyer le code", ar: "أرسل الرمز" } satisfies L10n,
    sending: { fr: "Envoi du code…", ar: "جاري إرسال الرمز…" } satisfies L10n,
    wait: {
      fr: "Renvoyer le code dans {n}s",
      ar: "أعد الإرسال خلال {n} ث",
    } satisfies L10n,
    rate: {
      fr: "Attendez 90 secondes avant de redemander un code.",
      ar: "انتظر 90 ثانية قبل طلب رمز جديد.",
    } satisfies L10n,
  },
  verify: {
    title: { fr: "Votre code", ar: "رمزك" } satisfies L10n,
    body: {
      fr: "Saisissez le code envoyé à",
      ar: "أدخل الرمز المرسل إلى",
    } satisfies L10n,
    code: { fr: "Code à 6 chiffres", ar: "رمز من 6 أرقام" } satisfies L10n,
    submit: { fr: "Se connecter", ar: "دخول" } satisfies L10n,
    connecting: { fr: "Connexion…", ar: "جاري الدخول…" } satisfies L10n,
    back: { fr: "Changer d'email", ar: "تغيير البريد" } satisfies L10n,
    invalid: { fr: "Code incorrect.", ar: "رمز غير صحيح." } satisfies L10n,
    expired: { fr: "Code expiré. Demandez-en un nouveau.", ar: "انتهت صلاحية الرمز." } satisfies L10n,
    locked: {
      fr: "Trop d'essais. Demandez un nouveau code.",
      ar: "محاولات كثيرة. اطلب رمزاً جديداً.",
    } satisfies L10n,
    suspended: { fr: "Ce compte est suspendu.", ar: "هذا الحساب معلّق." } satisfies L10n,
  },
  nav: {
    home: { fr: "Accueil", ar: "الرئيسية" } satisfies L10n,
    courses: { fr: "Cours", ar: "الدورات" } satisfies L10n,
    browse: { fr: "Catalogue", ar: "الدليل" } satisfies L10n,
    certificates: { fr: "Certificats", ar: "الشهادات" } satisfies L10n,
    profile: { fr: "Profil", ar: "الملف" } satisfies L10n,
    overview: { fr: "Aperçu", ar: "نظرة عامة" } satisfies L10n,
    students: { fr: "Élèves", ar: "الطلاب" } satisfies L10n,
    reviews: { fr: "Avis", ar: "التقييمات" } satisfies L10n,
    users: { fr: "Utilisateurs", ar: "المستخدمون" } satisfies L10n,
    applications: { fr: "Candidatures", ar: "الطلبات" } satisfies L10n,
    testimonials: { fr: "Témoignages", ar: "الشهادات" } satisfies L10n,
    sessions: { fr: "Sessions", ar: "الجلسات" } satisfies L10n,
    library: { fr: "Bibliothèque", ar: "المكتبة" } satisfies L10n,
    orders: { fr: "Demandes", ar: "الطلبات" } satisfies L10n,
    billing: { fr: "Facturation", ar: "الفوترة" } satisfies L10n,
    messages: { fr: "Messages", ar: "الرسائل" } satisfies L10n,
    settings: { fr: "Réglages", ar: "الإعدادات" } satisfies L10n,
    logout: { fr: "Déconnexion", ar: "خروج" } satisfies L10n,
  },
  empty: {
    courses: { fr: "Aucun cours pour l'instant.", ar: "لا دورات بعد." } satisfies L10n,
    students: { fr: "Aucun élève inscrit.", ar: "لا طلاب مسجّلين." } satisfies L10n,
    certificates: {
      fr: "Terminez un cours à 100 % pour obtenir un certificat.",
      ar: "أكمل دورة بنسبة 100٪ للحصول على شهادة.",
    } satisfies L10n,
    reviews: { fr: "Pas encore d'avis.", ar: "لا تقييمات بعد." } satisfies L10n,
    applications: { fr: "Aucune candidature en attente.", ar: "لا طلبات معلّقة." } satisfies L10n,
    sessions: { fr: "Aucune session active.", ar: "لا جلسات نشطة." } satisfies L10n,
    users: { fr: "Aucun utilisateur pour ce filtre.", ar: "لا مستخدمين لهذا التصفية." } satisfies L10n,
    orders: { fr: "Aucune demande WhatsApp pour l’instant.", ar: "لا طلبات واتساب بعد." } satisfies L10n,
  },
  student: {
    continue: { fr: "Continuer", ar: "متابعة" } satisfies L10n,
    progress: { fr: "Progression", ar: "التقدم" } satisfies L10n,
    activity: { fr: "Activité récente", ar: "النشاط الأخير" } satisfies L10n,
    markDone: { fr: "Marquer comme vue", ar: "تعليم كمكتملة" } satisfies L10n,
    done: { fr: "Leçon vue", ar: "شوهدت" } satisfies L10n,
    notes: { fr: "Notes", ar: "ملاحظات" } satisfies L10n,
    lessons: { fr: "Leçons", ar: "الدروس" } satisfies L10n,
    enrollWp: { fr: "S'inscrire", ar: "التسجيل" } satisfies L10n,
    open: { fr: "Ouvrir", ar: "فتح" } satisfies L10n,
  },
  teacher: {
    create: { fr: "Nouveau cours", ar: "دورة جديدة" } satisfies L10n,
    submit: { fr: "Envoyer pour validation", ar: "إرسال للمراجعة" } satisfies L10n,
    published: { fr: "En ligne", ar: "منشور" } satisfies L10n,
    draft: { fr: "Brouillon", ar: "مسودة" } satisfies L10n,
    pending: { fr: "En revue", ar: "قيد المراجعة" } satisfies L10n,
    addModule: { fr: "Ajouter un module", ar: "إضافة وحدة" } satisfies L10n,
    addLesson: { fr: "Ajouter une leçon", ar: "إضافة درس" } satisfies L10n,
    videoUrl: { fr: "URL vidéo (Publitio)", ar: "رابط الفيديو" } satisfies L10n,
    thumbUrl: { fr: "URL miniature", ar: "رابط الصورة" } satisfies L10n,
    pickLibrary: { fr: "Choisir dans la bibliothèque", ar: "اختيار من المكتبة" } satisfies L10n,
  },
  admin: {
    approve: { fr: "Approuver", ar: "قبول" } satisfies L10n,
    reject: { fr: "Refuser", ar: "رفض" } satisfies L10n,
    suspend: { fr: "Suspendre", ar: "تعليق" } satisfies L10n,
    restore: { fr: "Réactiver", ar: "إعادة تفعيل" } satisfies L10n,
    forceLogout: { fr: "Déconnecter", ar: "إنهاء الجلسة" } satisfies L10n,
    enroll: { fr: "Inscrire un élève", ar: "تسجيل طالب" } satisfies L10n,
    viewStudents: { fr: "Voir les élèves", ar: "عرض الطلاب" } satisfies L10n,
    editCourse: { fr: "Modifier", ar: "تعديل" } satisfies L10n,
    studentCount: { fr: "{n} élèves", ar: "{n} طلاب" } satisfies L10n,
    studentCountOne: { fr: "1 élève", ar: "طالب واحد" } satisfies L10n,
    studentCountNone: { fr: "Aucun élève", ar: "لا طلاب" } satisfies L10n,
    enrolledOn: { fr: "Inscrit le", ar: "تاريخ التسجيل" } satisfies L10n,
    lastActive: { fr: "Dernière activité", ar: "آخر نشاط" } satisfies L10n,
    completed: { fr: "Terminé", ar: "مكتمل" } satisfies L10n,
    inProgress: { fr: "En cours", ar: "قيد التقدم" } satisfies L10n,
    averageProgress: { fr: "Progression moyenne", ar: "متوسط التقدم" } satisfies L10n,
    finishedCount: { fr: "Terminés", ar: "أكملوا" } satisfies L10n,
    editUser: { fr: "Fiche", ar: "الملف" } satisfies L10n,
    resetAccess: { fr: "Réinitialiser l’accès", ar: "إعادة ضبط الدخول" } satisfies L10n,
    resetAccessBody: {
      fr: "Ferme toutes les sessions et envoie un nouveau code de connexion par email. Il n’y a pas de mot de passe.",
      ar: "يُغلق كل الجلسات ويرسل رمز دخول جديداً بالبريد. لا توجد كلمة مرور.",
    } satisfies L10n,
    homeBlock: { fr: "Bloc catégories (accueil)", ar: "قسم الفئات (الرئيسية)" } satisfies L10n,
    homeBlockBody: {
      fr: "Afficher ou masquer la bande de catégories sur le site public.",
      ar: "إظهار أو إخفاء شريط الفئات على الموقع العام.",
    } satisfies L10n,
    showHomeBlock: { fr: "Afficher sur l’accueil", ar: "إظهار في الرئيسية" } satisfies L10n,
    hideHomeBlock: { fr: "Masquer sur l’accueil", ar: "إخفاء من الرئيسية" } satisfies L10n,
    showOnHome: { fr: "Afficher cette catégorie", ar: "إظهار هذه الفئة" } satisfies L10n,
    hideOnHome: { fr: "Retirer de l’accueil", ar: "إزالة من الرئيسية" } satisfies L10n,
    libraryUpload: { fr: "Téléverser une vidéo", ar: "رفع فيديو" } satisfies L10n,
    librarySync: { fr: "Synchroniser Publitio", ar: "مزامنة Publitio" } satisfies L10n,
    libraryEmpty: {
      fr: "Aucune vidéo dans la bibliothèque pour l’instant.",
      ar: "لا فيديوهات في المكتبة بعد.",
    } satisfies L10n,
    libraryReused: {
      fr: "Fichier déjà présent — réutilisé, pas de nouvel envoi.",
      ar: "الملف موجود مسبقاً — أُعيد استخدامه دون رفع جديد.",
    } satisfies L10n,
    libraryUploaded: { fr: "Vidéo ajoutée à la bibliothèque.", ar: "أُضيف الفيديو إلى المكتبة." } satisfies L10n,
    useOnLesson: { fr: "Utiliser sur une leçon", ar: "استخدام في درس" } satisfies L10n,
    videoAttached: { fr: "Vidéo liée à cette leçon.", ar: "فيديو مرتبط بهذا الدرس." } satisfies L10n,
    videoEmpty: { fr: "Pas encore de vidéo — choisissez dans la bibliothèque ou téléversez.", ar: "لا فيديو بعد — اختر من المكتبة أو ارفع ملفاً." } satisfies L10n,
    deleteLesson: { fr: "Supprimer la leçon", ar: "حذف الدرس" } satisfies L10n,
  },
  save: { fr: "Enregistrer", ar: "حفظ" } satisfies L10n,
  cancel: { fr: "Annuler", ar: "إلغاء" } satisfies L10n,
};
